"use client";

import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import Header from "./components/header/Header";
import Footer from "./components/footer/Footer";
import { Box } from "@mui/material";
import { BrowserRouter as Router } from "react-router-dom";

const inter = Inter({ subsets: ["latin"] });

const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <Router>
        <html lang="en">
          <body className={inter.className}>
            <Header />
            <Box component="main">{children}</Box>
            <Footer />
          </body>
        </html>
      </Router>
    </ClerkProvider>
  );
}
